# Generated by Django 4.1 on 2022-11-04 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('prid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'foodie_products',
            },
        ),
        migrations.RenameField(
            model_name='usersignin',
            old_name='mail',
            new_name='password',
        ),
        migrations.CreateModel(
            name='userrecord',
            fields=[
                ('usrrcdid', models.AutoField(primary_key=True, serialize=False)),
                ('usrname', models.CharField(max_length=100)),
                ('usrcontact_num', models.CharField(max_length=100)),
                ('usraddress', models.CharField(max_length=100)),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodie.usersignin')),
            ],
            options={
                'db_table': 'foodie_userrcd',
            },
        ),
    ]
