# Generated by Django 4.1 on 2022-11-30 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0002_products_rename_mail_usersignin_password_userrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartsaved',
            fields=[
                ('cartid', models.AutoField(default=True, primary_key=True, serialize=False)),
                ('product_qty', models.IntegerField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cartsaved',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='prid',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersignin',
            name='usrid',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='products',
            table=None,
        ),
        migrations.DeleteModel(
            name='userrecord',
        ),
        migrations.AddField(
            model_name='cartsaved',
            name='prid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='foodie.products'),
        ),
        migrations.AddField(
            model_name='cartsaved',
            name='usrid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='foodie.usersignin'),
        ),
         '''migrations.AddField(
            model_name='cartsaved',
            name='product_qty',
            field=models.IntegerField(null=True, to='foodie.products'),
        ), '''   
    ]
